// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iialxxzyqdxvymscociv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpYWx4eHp5cWR4dnltc2NvY2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODQ5MDAsImV4cCI6MjA3MjM2MDkwMH0.gKSdQ1brmcXqOx7AoaNLSUPYXFcP2MqPyyvozPadzhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});